strict-sigcheck = true

[YouTube-ReVanced-Extended]
enabled = true
brand = "ReVanced-Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
changelog-keywords = ["YouTube"]
arch = "arm64-v8a"
version = "auto"
patcher-args = "-e 'Custom Shorts action buttons' -OiconType='round' -e 'Force player buttons background' -OBackgroundColor='#99000000' -e 'Hide shortcuts' -Oexplore=true -Osubscriptions=true -Osearch=true -e 'Overlay buttons' -OiconType='rounded' -ObottomMargin='0.1dip' -e 'Settings for YouTube' -OrvxSettingsLabel='ReVanced Extended' -e 'Snack bar components' -OcornerRadius='100.0dip' -OapplyCornerRadiusToPlaylistBottomBar=true -OdarkThemeBackgroundColor='@android:color/black' -OlightThemeBackgroundColor='@android:color/white' -OstrokeColor='?attr/ytChipBackground' -e 'Visual preferences icons for YouTube' -OsettingsMenuIcon='revanced'"

[YouTube-ReVanced-Extended.patches]
"github:anddea/revanced-patches" = { version = "dev", include = ["Hide Shorts dimming"], exclude = ["Enable debug logging", "Translations for YouTube"] }

[YouTube-Music-ReVanced-Extended]
enabled = true
brand = "ReVanced-Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
changelog-keywords = ["YouTube Music"]
arch = "arm64-v8a"
version = "auto"
patcher-args = "-e 'Settings for YouTube Music' -OrvxSettingsLabel='ReVanced Extended' -e 'Visual preferences icons for YouTube Music' -OsettingsMenuIcon='revanced'"

[YouTube-Music-ReVanced-Extended.patches]
"github:anddea/revanced-patches" = { version = "dev", include = ["Disable music video in album"], exclude = ["Enable debugging", "Translations for YouTube Music"] }

[YouTube]
enabled = true
brand = "Morphe"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
changelog-keywords = ["YouTube"]
arch = "arm64-v8a"
version = "exp"
patcher-args = "--force"

[YouTube.patches]
"github:MorpheApp/morphe-patches" = { version = "dev", exclude = ["Custom branding", "Enable debugging", "Disable play store updates"] }

[YouTube-Music]
enabled = true
brand = "Morphe"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
changelog-keywords = ["YouTube Music"]
arch = "arm64-v8a"
version = "exp"

[YouTube-Music.patches]
"github:MorpheApp/morphe-patches" = { version = "dev", exclude = ["Custom branding", "Enable debugging", "Disable play store updates"] }

[Reddit]
enabled = true
brand = "Morphe"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
version = "exp"
patcher-args = "-e 'Colorize comment indent lines' -OindentLineColors1='#0066FF' -OindentLineColors2='#FF2E88' -OindentLineColors3='#9B5CFF' -OindentLineColors4='#2DE2E6' -OindentLineColors5='#FF5FA2' -OindentLineColors6='#FF8A3D' -OindentLineColors7='#FFD166' -OindentLineColors8='#3CFF7F' -OisCurrentLevelOnly=true"

[Reddit.patches]
"github:MorpheApp/morphe-patches" = { version = "dev" }
"github:jkennethcarino/adobo" = { version = "dev", include = ["Disable home feed auto-refresh", "Disable post detail swipe"], exclude = ["Hide post view counts", "Disable screenshot banner", "Open external links directly", "Sanitize share links"] }

[Twitter]
enabled = true
brand = "Piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
changelog-keywords = ["Twitter"]
arch = "arm64-v8a"

[Twitter.patches]
"github:crimera/piko" = { version = "dev", include = ["Browse tweet object"] }

[Instagram]
enabled = true
brand = "Piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
# github-dlurl = "https://github.com/imPratyoosh/APKs-storage/releases/tag/instagram"
changelog-keywords = ["Instagram"]
arch = "arm64-v8a"
patcher-args = "-e 'Clone' -OpackageName='com.instagram' -OappName='Instagram'"

[Instagram.patches]
"github:crimera/piko" = { version = "dev", exclude = ["Change version code"] }

[Gboard]
enabled = true
brand = "JasonWu"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard/"
arch = "arm64-v8a"
patcher-args = "-e 'Package Rename' -Oapp_display_name='Gboard Mod'"

[Gboard.patches]
"github:jasonwu1994/Gboard-patches" = []

[Pinterest]
enabled = true
brand = "Browzomje"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pinterest/pinterest-one-destination-for-a-world-of-inspiration/"
arch = "arm64-v8a"

[Pinterest.patches]
"github:browzomje/browzomje-patches" = { version = "dev" }
"github:MorpheApp/morphe-patches" = []

[Google-Photos]
enabled = false
brand = "GPhotos"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
version = "latest"
arch = "arm64-v8a"

[Google-Photos.patches]
"github:RookieEnough/De-Vanced" = []
